from .business_sales import create_business_sales_layout
from .customer_behavior import create_customer_behavior_layout
from .advertising_marketing import create_advertising_marketing_layout
from .service_quality import create_service_quality_layout

